### ISSUE TITLE
Dog Ear Not Working

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#237] opened 2020-12-21 13:28 UTC
I was testing the latest version of SNaP (Master Branch) and when I tried dog-ear-ing partitions, my numbers were not being reflected in the drawings (no numbers were being reflected):

![Dog Ear Not Working](https://user-images.githubusercontent.com/61025894/102781784-7b9b7980-4355-11eb-964f-fbcaedb19de2.png)

It has been a while since I tested dog ear partitions I think so I'm not sure when it stopped working but this needs to be fixed prior to sending out the update to users. Unsure if it has anything to do with https://github.com/CCDevNelson/Snap-Updates/issues/191 but I didn't think anything had been changed for this in the current build of SNaP.

**Comment by TedCC1209** [comment] 2020-12-21 13:38
When I put a top shelf in above those sections above (kept the dog ear numbers in there even though it wasn't being reflected in the scene), it adjusted the depth of the top shelf as though the dog ear was working.

**Comment by ClassyTeddy** [comment] 2020-12-21 14:22
I cannot seem to replicate the dog ears not showing up in the drawing. What are the other setting that you have enabled on that partition? Another prompt might be causing an error, so I need to replicate it exactly and try to find where the issue is.

**Comment by TedCC1209** [comment] 2020-12-21 14:45
For this particular set of partitions the settings where as follows:

![Dog Ear Partition Prompts 1](https://user-images.githubusercontent.com/61025894/102788662-3cbef100-4360-11eb-903d-0a0d8a4b3c3d.png)

![Dog Ear Partition Prompts 2](https://user-images.githubusercontent.com/61025894/102788672-3f214b00-4360-11eb-8d29-57ef2986475a.png)

![Dog Ear Partition Prompts 3](https://user-images.githubusercontent.com/61025894/102788677-40eb0e80-4360-11eb-96ba-21b331c8d236.png)

The dog ears are working in another test job I am doing so I am also trying to figure out what is different with the one that isn't working for me.

**Comment by ClassyTeddy** [comment] 2020-12-21 14:50
It is still working for me. What other assemblies do you have that are apart of the partition?

**Comment by TedCC1209** [comment] 2020-12-21 14:50
Is it the tall partitions causing the issue? Here is another one where a shorter partition (37H) shows the dog ear but the taller partitions (62H) do not:

![Dog Ear 1](https://user-images.githubusercontent.com/61025894/102789257-1b123980-4361-11eb-98db-715c535deeeb.png)

![Dog Ear 2](https://user-images.githubusercontent.com/61025894/102789272-1e0d2a00-4361-11eb-9cdb-c87ace444189.png)

@AntonioGloria what were the changes you made to how the partitions were drawn so that we got the straight lines in the rendering? Could that be contributing to this?

Thanks, 

Ted

**Comment by TedCC1209** [comment] 2020-12-21 14:52
By just changing the 62H partitions to 37H the dog ear showed up in the previous test:

![Dog Ear 3](https://user-images.githubusercontent.com/61025894/102789454-6cbac400-4361-11eb-94af-b5a159ec33eb.png)

**Comment by TedCC1209** [comment] 2020-12-21 14:54
Same with the original test job, just had to change it to shorter partitions to see the dog ear:

![Dog Ear 4](https://user-images.githubusercontent.com/61025894/102789695-b2778c80-4361-11eb-8207-f0c96a5c4ec0.png)

**Comment by AntonioGloria** [comment] 2020-12-21 15:07
Hi @TedCC1209,
The change I made was to add a Remesh modifier in the .blend file for the Closet Panel assembly, on top of the modifiers that adjust that part's dimensions. It might be contributing to this issue. I can try to replicate these partition settings and tweak the values on the modifier to see if that solves the issue.

**Comment by ClassyTeddy** [comment] 2020-12-21 15:10
I can confirm that this was not an issue on previous branches, so I am going to run through each branch recently merged and try to find which branch causes it.

**Comment by ClassyTeddy** [comment] 2020-12-21 15:27
I can confirm that this issue appears to originate from the 3D Labels Branch

**Comment by AntonioGloria** [comment] 2020-12-22 19:41
Hello @TedCC1209
I got the dog ears working again.
![image](https://user-images.githubusercontent.com/74732175/102926831-55f89800-445b-11eb-8efd-da64753becb2.png)
The fix is available here: https://github.com/nailsonlandim/SNaP-Dev/tree/3DLabels

**Comment by TedCC1209** [comment] 2020-12-22 20:49
Looks good to me, thanks!

**Closed** 2021-01-19 18:55 UTC
Labels: bug
