### ISSUE TITLE
Dura White not available, program crashing when I try to put first partitions in

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#115] opened 2020-07-14 18:03 UTC
The master branch doesn't have dura white or dura almond available to choose (which should be the default in the master branch right now). Fog grey is now what pops up as the default material selection (and select walnut is the default door/drawer face material for some reason) and my program is crashing when I try to put in partitions without selecting a different color (if I manually select a different color it doesn't crash). My guess is something happened with the new csv?

![image](https://user-images.githubusercontent.com/61025894/87460340-96590d80-c5c1-11ea-8111-e88002212e19.png)

**Comment by RyanMDev** [comment] 2020-07-14 18:21
I can fix this.

**Comment by ClassyTeddy** [comment] 2020-07-14 18:43
Alright, I think part of the problem is we changed `Dura White` and `Dura Almond` to `Duraply White` and `Duraply Almond` in the .csv, so the blend files should have their names changed as well.

**Comment by RyanMDev** [comment] 2020-07-14 19:00
CCDevNelson/SNaP-Dev@890f8fd73469db62800ec5001a7e323abed93a14 updates material names.

**Comment by ClassyTeddy** [comment] 2020-07-14 19:02
Looks good to me.

**Comment by RyanMDev** [comment] 2020-07-14 19:08
'Fog Grey' and a few other colors may still take longer to load but this will be fixed as part of performance optimizations related to lag being caused when drawing products:
CCDevNelson/SNaP-Dev#210

**Comment by TEDSTANDAGE** [comment] 2020-07-14 20:38
Fixed the dura and crashing issues for me, thank you

**Closed** 2020-07-15 15:45 UTC
Labels: bug
