### ISSUE TITLE
Set back filler option

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#252] opened 2020-12-22 14:42 UTC
We should allow for fillers to be moved back and not just be flush with the front of the partition--we set back the filler sometimes to help avoid an obstacle that is on a wall (like a light switch) or when the left/right return wall is less deep than the partition. Ideally this setback option would go where the left/right end deduction option currently is and the left/right end deduction option would be moved (see https://github.com/CCDevNelson/Snap-Updates/issues/221).

**Comment by TedCC1209** [comment] 2021-01-12 15:28
J, while you are doing this, can you move the filler options so there is a left filler column and a right filler column? Essentially just switching the location of where the "Left End Deduction" and "Right Filler Amount" options currently are. Then you can create a new row for the filler setback amount to go right under the row for the left and right filler amounts.

![FILLER COLUMNS](https://user-images.githubusercontent.com/61025894/104334880-1d733980-54b0-11eb-8f90-82e1e73e2418.png)

**Comment by JJanneh** [comment] 2021-01-12 15:30
Ok thanks for the ScreenGrab as well.

**Comment by JJanneh** [comment] 2021-01-12 16:59
![Screenshot (45)](https://user-images.githubusercontent.com/76751383/104346453-adb77b80-54bc-11eb-98c2-a2fef9e1507d.png)
New row for the filler setback amount added

**Comment by TedCC1209** [comment] 2021-01-12 17:10
Thanks for making the left/right columns, next please put the setback amount row below the filler amount row.

Also, because this section affects more than just filler options, please change the words "Filler Options:" (circled below) to say "Filler and Left/Right End Options:"

![Filler Options](https://user-images.githubusercontent.com/61025894/104347860-52868880-54be-11eb-806f-ffa960a72303.png)

**Comment by JJanneh** [comment] 2021-01-12 17:41
![Screenshot (50)](https://user-images.githubusercontent.com/76751383/104351297-777cfa80-54c2-11eb-97d8-35b3f35bc5fc.png)
Renamed & Moved setback amount

**Comment by TedCC1209** [comment] 2021-01-12 18:43
Thanks J, please also get rid of the capitalization of the letter B in Setback--It should say "Setback" instead of "SetBack". When you are ready for us to test the functionality of this please give us the branch name. Thanks, Ted

**Comment by JJanneh** [comment] 2021-01-12 20:03
Branch location Custom-partition-depth
![Screenshot (52)](https://user-images.githubusercontent.com/76751383/104365604-71444980-54d5-11eb-8efe-b1b18468afd8.png)

**Comment by JJanneh** [comment] 2021-01-13 16:21
![set-back-filler-option](https://user-images.githubusercontent.com/76751383/104478941-1a477e80-5580-11eb-83c6-f70ee8c746dc.png)
@ClassyTeddy I tried to move the whole object and just got a upper movement. I was thinking about adding new_method to completely move this item along the Y Axis not completely sure. I'm requesting some guidance on this if possible. Thanks

**Comment by ClassyTeddy** [comment] 2021-01-13 20:03
That is actually really odd, I have never seen an object behave that way unintentionally. It shouldn't be necessary to create a new function. Are you sure you you changed the objects `.y_loc` and not it's `.y_rot`?

**Comment by JJanneh** [comment] 2021-01-13 20:49
Ok. right_filler.y_loc("-Last_Depth+Right_End_Deduction", [Last_Depth, Right_End_Deduction])
right_filler.y_rot(value = -90)
Goal is to move along the Y axis like the top part did. I was not able to move the complete object along the Y Axis fully. 
![Screenshot (59)](https://user-images.githubusercontent.com/76751383/104507750-758b6800-55a4-11eb-92a4-2a31e85e2839.png)

**Comment by ClassyTeddy** [comment] 2021-01-13 20:56
What branch are you currently working on?

**Comment by JJanneh** [comment] 2021-01-13 20:59
Set-back-filler-option branch

**Comment by ClassyTeddy** [comment] 2021-01-13 21:03
Can you update it with the current changes? At the moment, I don't have the same options as you, and it is moving along the axis properly for me.

**Comment by ClassyTeddy** [comment] 2021-01-13 21:16
Right. I know about those options. So I pulled the commit and it still is the same. I looked at the commit history, and I am having trouble finding your changes. For one, most of your commits look like this, and only sometimes does it actually have a change to the data_closet_carcass.py file:
![Commit Example](https://user-images.githubusercontent.com/62624110/104511312-bd60be00-55a9-11eb-8f85-c6bb84ec9b35.png)

So, I can't actually see any changes made to the closet carcass with the most recent commit.

**Comment by JJanneh** [comment] 2021-01-13 21:24
I just made another change and requested you.
Thanks for all the help man

**Comment by ClassyTeddy** [comment] 2021-01-13 21:37
So again, I cannot mimic the problem you are having with the filler where it rotates instead of moving backwards. I went back to your photo and noticed that the green line pointed to the y-rotation and it's value was 99.1, which does in fact rotate it in that direction and have it mimic the photo. So the pink y is actually the location driver. If you select it, it will show you what equation is determining the value, like this:

![Driver Function Example](https://user-images.githubusercontent.com/62624110/104513245-8f30ad80-55ac-11eb-9857-247106b1ced8.png)


So the left 3 values are the location values, and cannot be manually changed because a driver function is determining their value. Try placing another partition and changing the values in the prompt menu again for me.

**Comment by JJanneh** [comment] 2021-01-13 21:50
Ok. @ClassyTeddy I just backspaced Y Location (**Depth Deduction**) area to 0 then changed the Y rotation -89.6 
![Location](https://user-images.githubusercontent.com/76751383/104514292-37934180-55ae-11eb-91c6-3fa2edb6dae1.PNG)

**Comment by ClassyTeddy** [comment] 2021-01-13 21:57
Right, so I wanted you to change the value in the Partition Prompts Menu on a new partition. 

A location of 0 will move the filler to the back if the partition because that is the local 0 y location. (0,0,0) is actually the bottom, back, left corner of an assembly. Changing the rotation isn't necessary.

So place a new partition, and only use the construction options in the prompts menu to move the filler back.

**Comment by JJanneh** [comment] 2021-01-13 22:09
@ClassyTeddy Ok. When in the construction options in the prompts menu moving back and forward just made the filler larger. Only in the other menu appears to shift the filler 
![Screenshot (62)](https://user-images.githubusercontent.com/76751383/104516025-e20c6400-55b0-11eb-8429-f59c8336a073.png)
Assembly Menu:
![Partition_](https://user-images.githubusercontent.com/76751383/104516063-f5b7ca80-55b0-11eb-88e7-4038b791b7ee.PNG)

**Comment by ClassyTeddy** [comment] 2021-01-13 22:23
Ok, so you are currently moving the y location of the partition and moving it back which is not what I asked. Don't worry about the assembly menu. Just worry about the prompts menu. 

Let's back up a bit.

You said you were trying to move the left filler along the y-axis, and when you tried, you said that "you just got upper movement". What I am trying to say is that you were accidentally rotating the object in the assembly menu.

What I was trying to point out was that in the prompts menu, the 'Left End Deduction' option is currently moving the filler back on the y-axis (as well as deducting length on the left partition). 

So what Ted wants is for 'Left Filler Setback Amount' to move the filler on the y-axis without deducting length on the left partition. Does that make sense?

**Comment by JJanneh** [comment] 2021-01-14 14:03
Yes that makes sense.

**Comment by JJanneh** [comment] 2021-01-14 16:09
![Screenshot (63)](https://user-images.githubusercontent.com/76751383/104616936-1da63d00-5648-11eb-9b40-ed3466d07250.png)
Changed prompts @ClassyTeddy

**Comment by ClassyTeddy** [comment] 2021-01-14 16:21
I don't see the prompts menu open. What did you change?

**Comment by JJanneh** [comment] 2021-01-14 16:26
Line 255
left_filler.y_loc("Length_1+Left_End_Deduction", [Depth_1,
Left_End_Deduction])

**Comment by JJanneh** [comment] 2021-01-14 16:30
![Prompts_menu](https://user-images.githubusercontent.com/76751383/104619420-13d20900-564b-11eb-8c55-9207e480372d.PNG)

**Comment by ClassyTeddy** [comment] 2021-01-14 16:46
Ah so you changed the `.y_loc` driver for the left filler. 

So, I noticed that what you did was change `-Depth_1` to `Length_1`. This will cause an error in the driver function, causing it to calculate to 0. The reason for the error is that `Length_1` doesn't exist as far as the driver function is concerned. It only knows about 2 variables, which are `[Depth_1, Left_End_Deduction]`. If you want to use more or different variables, you need to add them to this list.

Also, this still isn't quite how we need it to function, even if it wasn't throwing an error. 

What we want to happen is for the filler to be "Flush" with the end of the partition, meaning that it stays with the end of the partition at all times. It was already doing that when the driver functions looked like this:

`left_filler.y_loc("-Depth_1+Left_End_Deduction", [Depth_1, Left_End_Deduction])`

So we want it like this to start. Then, we ALSO want it have the ability to be set back even further, and bot be flush with the partition. That is why you added the `Left Filler Setback Amount` prompt.

So we want the driver to look like this:

`left_filler.y_loc("-Depth_1+Left_End_Deduction+
Left_Filler_Setback_Amount", [Depth_1, Left_End_Deduction,Left_Filler_Setback_Amount])`

Let me know if this all makes sense.

**Comment by JJanneh** [comment] 2021-01-14 16:57
Ok yeah that makes sense. Thanks again your help is greatly appreciated. I will make these changes and see how things go.

**Comment by JJanneh** [comment] 2021-01-14 17:47
![Screenshot (64)](https://user-images.githubusercontent.com/76751383/104628782-e0e14280-5655-11eb-805e-bcf4f8795f9b.png)
@ClassyTeddy

**Comment by ClassyTeddy** [comment] 2021-01-14 17:53
What do you need my help with J?

**Comment by JJanneh** [comment] 2021-01-14 17:54
This seems to be working thanks.

**Comment by JJanneh** [comment] 2021-01-19 19:50
![Screenshot (85)](https://user-images.githubusercontent.com/76751383/105085333-d7404c00-5a54-11eb-9329-d817cfde1585.png)
Set-back-filler-option Branch Testing

**Comment by SeanRadvan** [comment] 2021-01-19 20:36
While testing this, it looks like the filler amount is subtracting from the
overal width, is this correct? I assumed filler would be say 2" filler on a
40" cabinet for an overall with of 42". This appears to be 2" filler on a
40" cabinet is 40" overall, with 38" cabinet width.

**Comment by TedCC1209** [comment] 2021-01-19 20:56
> While testing this, it looks like the filler amount is subtracting from the overal width, is this correct? I assumed filler would be say 2" filler on a 40" cabinet for an overall with of 42". This appears to be 2" filler on a 40" cabinet is 40" overall, with 38" cabinet width.
> […]

Sean, are you saying there is an issue? The widths are working as they always have been. The "Width" you see on the upper left of the opening start prompts is the exterior width of that entire hanging opening assembly, which includes the fillers as part of the assembly. The interior widths of the openings (that you see in the Opening Sizes menu) adjust according to the number of partitions (0.75" width each), filler sizes, etc. So, when you change the filler width, the overall exterior width of the assembly is not going to change--only the interior widths as shown on the Opening Sizes menu will change.

**Comment by SeanRadvan** [comment] 2021-01-19 20:59
Ok so it appears to be working as intended then, I just didnt know how
classy did fillers, and I was used to it being the other way around.

**Comment by TedCC1209** [comment] 2021-01-19 21:01
@JJanneh The setback option looks to be working correctly, thank you.

**Comment by TedCC1209** [comment] 2021-02-03 17:30
So this one looks to be good to go, a little apprehensive as the branch was created before some of the recent hot fixes and updates. @ClassyTeddy if @JJanneh needs to update the branch before merging please advise. Thanks, Ted

**Comment by JJanneh** [comment] 2021-02-03 17:46
Thanks @TedCC1209 I can update the branch now it looks to need update 1.2.4

**Comment by ClassyTeddy** [comment] 2021-02-03 18:03
Do not update the branch through SNaP. Doing so will remove any changes made on the branch.

You can either update the branch by merging in the current master, or if it is good to go we can just merge this branch into the master.

**Closed** 2021-03-29 13:49 UTC
Labels: enhancement
