### ISSUE TITLE
Prepare 2D Views error 1.2.2

### ISSUE THREAD

**Issue by SeanRadvan** [CCDevNelson/Snap-Updates#282] opened 2021-01-22 17:03 UTC
https://mail.google.com/mail/u/0?ui=2&ik=3093dcecd3&attid=0.1&permmsgid=msg-f:1689544364517952714&th=177277a5df5b0cca&view=fimg&disp=thd&attbid=ANGjdJ_A4At73VBELoHhlyowozKlSpZTMiUzH7FBFghPN3WyNf9pUsVe-yY3TP-XaTDUgX-Qb_vRtpXbGwkrDC6rUuP8HyyK0ayOiD1h1hXrf5nu-XsifSLpg2DnER4&ats=2524608000000&sz=w1920-h937
End user is apparently running into this issue when preparing 2D views on an updated version of snap. According to them, they deleted the extra drawer / door and loaded snap defaults. This room was drawn after that. I am having them test a small room to see if its just specific parts breaking it.

**Comment by TedCC1209** [comment] 2021-01-22 17:14
I can't see anything on the link you sent, can you share it a different way please?

**Comment by SeanRadvan** [comment] 2021-01-22 17:44
![image](https://user-images.githubusercontent.com/54151330/105525841-d569c900-5c9e-11eb-9080-38cef4e46596.png)

**Comment by RyanMDev** [comment] 2021-01-22 17:47
The room .blend file for this would be helpful as well.

**Comment by RyanMDev** [comment] 2021-01-22 18:00
The following conditional statement is failing to set the `opng_x_pos` variable. Notice that this only takes into account wall angles: 0, 180, 90, -90. My guess without seeing the room file would be that this is failing because the user is using a custom room with angled walls that are anything other than: 0, 180, 90, -90 degrees.

            # Depending on wall angle, our "X-axis" is different.
            if wall_angle in [0, 180]:
                opng_x_pos = self.get_object_global_location(opening)[0]
            elif wall_angle in [90, -90]:
                opng_x_pos = self.get_object_global_location(opening)[1]
            positions_dict[opening] = opng_x_pos

https://github.com/CCDevNelson/SNaP-Dev/blob/739914444e98042cfece248e195ffe26b2b850ec/SNaP/2.78/scripts/addons/snap_db/fd_2dviews/__init__.py#L1592-L1597

**Comment by SeanRadvan** [comment] 2021-01-22 19:39
Confirmed with end user, he did have a 45 degree wall.

**Comment by nailsonlandim** [comment] 2021-01-22 19:49
@SeanRadvan does this 45-degree wall has any assembly on it?

**Comment by SeanRadvan** [comment] 2021-01-22 19:52
@nailsonlandim As far as I know, yes it did.

**Comment by sarahhightower** [comment] 2021-01-22 21:52
@nailsonlandim I notice you said that that it is "failing because the user is using a custom room with angled walls that are anything other than: 0, 180, 90, -90 degrees." To clarify, does the new version not allow us to do any other angles? 45 and 135 angles are also common variations and sometimes we may even have to draw walls outside of the 45 degree wall standard. 

Also, FYI, I did a test with a 135 degree angled wall and also received an error. 

![SNaP_  C__Users_shightower_Desktop_Angled Wall blend  1_22_2021 2_51_05 PM](https://user-images.githubusercontent.com/72047269/105552568-56d25300-5cc1-11eb-83dc-e1aab8fe4562.png)

**Comment by nailsonlandim** [comment] 2021-01-22 22:20
Thank you @SeanRadvan , @sarahhightower and @TedCC1209 for the prompt feedback.

I changed it to rely on trigonometry instead of fixed values. So you can have angles like 30 degrees...

![image](https://user-images.githubusercontent.com/70038700/105554537-55675180-5ce6-11eb-8ca2-f12d2c46a0f3.png)

and right angles works just like before.

![image](https://user-images.githubusercontent.com/70038700/105554708-aa0acc80-5ce6-11eb-84fb-f6d7b9f34082.png)

available at: https://github.com/nailsonlandim/SNaP-Dev/tree/issue_%23282-2d-views-error

**Comment by sarahhightower** [comment] 2021-01-22 23:03
Thanks Nailson! 

Is there a workaround for users who now have a version of SNaP that doesn't allow them to generate 2d views of plans that have angled walls?

**Comment by TedCC1209** [comment] 2021-01-22 23:12
This looks good to me! Nice work @nailsonlandim 

Can we get a pull request @ClassyTeddy ? @RyanMDev were you thinking of sending out a hotfix auto-update for this?

**Comment by RyanMDev** [comment] 2021-01-25 07:15
> @RyanMDev were you thinking of sending out a hotfix auto-update for this?

Yes.

**Comment by sarahhightower** [comment] 2021-01-25 16:58
I let the designer who brought up this issue that an auto update should be happening tomorrow. He is really anxious and is wondering if there's anything we can do to help him today to generate 2D views? Here's his file. 

https://drive.google.com/file/d/18OaOcUEImITqZmUI4NG1WxXhu3Hp9lrn/view?usp=sharing

**Comment by nailsonlandim** [comment] 2021-01-25 17:45
Hi @sarahhightower 

Here it comes. I hope it helps.

[2D Views - Master 1pp.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868456/2D.Views.-.Master.1pp.pdf)
[2D Views - Master 3pp.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868457/2D.Views.-.Master.3pp.pdf)
[2D Views - Master 2pp.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868458/2D.Views.-.Master.2pp.pdf)
[2D Views - Master Plan n Elev.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868460/2D.Views.-.Master.Plan.n.Elev.pdf)

**Comment by RyanMDev** [comment] 2021-01-25 17:50
The fix for this only invloves one file: `SNaP\2.78\scripts\addons\snap_db\fd_2dviews\__init__.py`

If you think he can handle replacing this file on his install, you can send him the updated one:

[fd_2dviews_fix_wall_X-axis_calculation.zip](https://github.com/CCDevNelson/Snap-Updates/files/5868445/fd_2dviews_fix_wall_X-axis_calculation.zip)

Looking at his error message, his path to the file to replace will be:
`C:\Users\robbi\Documents\SNaP-Dev-1.2.0\SNaP\2.78\scripts\addons\snap_db\fd_2dviews\__init__.py`

Navigating to this path he can replace this file with the updated one in the zip above.

**Comment by RyanMDev** [comment] 2021-01-25 17:51
I am going to look at #293 and see if a fix for that issue can be included in the hotfix as well.

**Comment by SeanRadvan** [comment] 2021-01-25 17:54
@sarahhightower I have the zip and will be available today if you want me to help them. They should have my email / phone number already, just let them know to contact me.

**Comment by kategodfrey** [comment] 2021-01-25 18:49
@SeanRadvan it looks like this fix might help Jerry in Dallas.

**Comment by kategodfrey** [comment] 2021-01-25 18:51
> I am going to look at #293 and see if a fix for that issue can be included in the hotfix as well.

@SeanRadvan it looks like this fix might help Jerry in Dallas.

**Comment by RyanMDev** [comment] 2021-01-25 19:21
> > I am going to look at #293 and see if a fix for that issue can be included in the hotfix as well.
> 
> @SeanRadvan it looks like this fix might help Jerry in Dallas.

Unfortunately, it will not.

The error from #293 stems from not being able to load a pull .blend file. Which is not code related to 2d views.

**Comment by SeanRadvan** [comment] 2021-01-25 19:47
Just got of phone with the user, the fix did not fix any previously drawn rooms, even after loading snap defaults, but they were able to draw a wall of -45 and do 2D Views after the fix.

**Comment by RyanMDev** [comment] 2021-01-25 22:15
Update 1.2.3 is ready to go and includes:

- 2D views fix for angled walls (this issue)
- Fix for #293

I will release this after hours today unless anyone sees a need to release it earlier.

**Comment by RyanMDev** [comment] 2021-01-26 01:10
> Just got of phone with the user, the fix did not fix any previously drawn rooms, even after loading snap defaults, but they were able to draw a wall of -45 and do 2D Views after the fix.

Do you have any more info on exactly how it did not fix any previously drawn rooms?

The file he provided (41110_Master Closet.blend) **was** a previously drawn room as it was previously drawn in 1.2.2 without the fix:

> I let the designer who brought up this issue that an auto update should be happening tomorrow. He is really anxious and is wondering if there's anything we can do to help him today to generate 2D views? Here's his file.
> 
> https://drive.google.com/file/d/18OaOcUEImITqZmUI4NG1WxXhu3Hp9lrn/view?usp=sharing

Nailson was then able to take this previously drawn room and create the following with the fix:

> Hi @sarahhightower
> 
> Here it comes. I hope it helps.
> 
> [2D Views - Master 1pp.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868456/2D.Views.-.Master.1pp.pdf)
> [2D Views - Master 3pp.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868457/2D.Views.-.Master.3pp.pdf)
> [2D Views - Master 2pp.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868458/2D.Views.-.Master.2pp.pdf)
> [2D Views - Master Plan n Elev.pdf](https://github.com/CCDevNelson/Snap-Updates/files/5868460/2D.Views.-.Master.Plan.n.Elev.pdf)

I am also able to reproduce Nailson's results with the fix using the previously drawn room file provided and preparing the 2D views.

**Comment by TylerStandage** [comment] 2021-03-08 21:15
@SeanRadvan do you know if this issue made it into 1.2.4?  From the above it looks like it did. Wondering if we can close this one.

**Comment by SeanRadvan** [comment] 2021-03-09 14:36
@TylerStandage As far as I'm aware yes it is resolved.

**Closed** 2021-03-09 15:54 UTC
Labels: bug
