### ISSUE TITLE
Topshelf covering filler

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#288] opened 2021-01-22 18:10 UTC
Topshelf should automatically cover left and right fillers rather than just only cover the top of the partition adjacent to the filler. Right now you have to "extend left" or "extend right" on the topshelf to get it to cover the filler, but I think this should be an easy automatic thing

**Comment by JJanneh** [comment] 2021-02-04 22:03
@TedCC1209 Where are Top Shelf size dimensions located? File location. I have to adjust the placement so it  automatically covers left and right fillers rather than just only cover the top of the partition adjacent to the filler.

**Comment by ClassyTeddy** [comment] 2021-02-04 22:17
The Top Shelves drivers are located in the data_closet_top.py file I believe.

**Comment by JJanneh** [comment] 2021-02-05 16:45
Ok found top_shelf @ClassyTeddy
A few questions where is the starting point for  "extend left" or "extend right"? Should placement of  the changes for the filler adjustments (0.75 to 2")  Here **def invoke**(self,context,event): this part is before the object is displayed or **if event.type ==** This part is where the action occurs after selection of the Top Shelf.  Should this be and **if else elif** statement or def invoke?

**Comment by ClassyTeddy** [comment] 2021-02-05 17:24
So I am really having trouble reading what you are trying to say. 

I believe that in the second half of your question you are looking at the drop operator of the Top Shelf. I know that your current goal is for the top shelf to adjust to left and right fillers accordingly. If that is the case, to have the Top Shelf automatically adjust on placement, you need to add logic some point after line 310, which looks like this:
```python
if not self.selected_panel_2:
```
This is the step in the logic where the user selects their second panel, and then the top shelf gets placed shortly after. Something to keep in mind that is very important, the user doesn't have to pick the left most and right most panels of a partition. They can pick any of the panels in the middle, which means you only want the top shelf to adjust for filler if the 1st selected panel is the left most, or if the 2nd selected panel is the right most.

This part of your question:
> Should this be and if else elif statement or def invoke?

`def invoke` is a built in function and without it, I am not sure that the Top Shelf would place at all. I am unsure about why you would want to replace it with an if, elif, else statement. 

I am also not sure about this question:
> A few questions where is the starting point for "extend left" or "extend right"? Should placement of the changes for the filler adjustments (0.75 to 2")

Are you asking what the default value for `Extend Left Amount` and `Extend Right Amount` are? Because the default should be 0. Where are you getting those two values? What are you trying to say about them?

Let me know if this helped at all.

**Comment by JJanneh** [comment] 2021-02-05 17:49
@ClassyTeddy What i was saying at the if not self.selected_panel_2: line 310 when the user selects any filler size. the top shelf can automatically cover the difference leaving the top surface completely covered.  Currently "extend left" or "extend right" has to be done manually. Image showing only right side extended need top shelf to cover both ends. 
![Screenshot (135)](https://user-images.githubusercontent.com/76751383/107069623-71b3c580-679f-11eb-9afc-9a7693edd052.png)

**Comment by ClassyTeddy** [comment] 2021-02-05 18:00
So I think I get what you were saying now, but I do notice that you use the following prompts:
```python
extend_left = self.insert.get_prompt("Extend To Left Panel")
extend_right = self.insert.get_prompt("Extend To Right Panel")
```
You should actually use `Extend Left Amount` and `Extend Right Amount`

**Comment by JJanneh** [comment] 2021-02-05 18:09
@ClassyTeddy Ok so if selected the Extend Left Amount and Extend Right Amount can be linked to the Top Shelf so it will adjust to the difference. Using the Extend Left Amount and Extend Right Amount difference automatically. So logic to check for the difference and extend the top shelf to cover the top surface completely. ok Thanks

**Comment by JJanneh** [comment] 2021-02-08 16:59
@ClassyTeddy When I tried this I got the Top Shelf to hover over the top but as soon as I clicked got error message. I used the get_var. I'm not sure maybe it's .get_prompt 
![error message 7](https://user-images.githubusercontent.com/76751383/107253038-25f95a00-69f3-11eb-9731-f631ce959ee4.PNG)
![Screenshot (144)](https://user-images.githubusercontent.com/76751383/107252608-c26f2c80-69f2-11eb-8243-86ef74509218.png)

**Comment by ClassyTeddy** [comment] 2021-02-08 17:02
`self` in this case is referring to the `DROP_OPERATOR_Place_Top`. You need to do `self.top_shelf.get_var()`

**Comment by JJanneh** [comment] 2021-02-08 17:20
@ClassyTeddy 
![Screenshot (147)](https://user-images.githubusercontent.com/76751383/107256856-44615480-69f7-11eb-9fe6-77fef0d0e296.png)
As soon as I changed it. looks like this 
![Screenshot (145)](https://user-images.githubusercontent.com/76751383/107256477-cac96680-69f6-11eb-81ce-61842d589f89.png)
![after added top_shelf](https://user-images.githubusercontent.com/76751383/107256292-8ccc4280-69f6-11eb-9773-e29cee4be160.PNG)

**Comment by ClassyTeddy** [comment] 2021-02-08 17:33
So the error says that at line 365, the variable `extend_left_amount` is not defined.

**Comment by JJanneh** [comment] 2021-02-08 22:20
@ClassyTeddy Ok so Removed extend_left_amount and extend_right_amount no errors ran again no errors. but still does not extend all the way with fillers selected. The action only goes from Left most partition and then it goes to the Right. Still have to manually increase the width. By right clicking and manually adjusting the size.

**Comment by ClassyTeddy** [comment] 2021-02-08 22:41
You didn't need to remove them @JJanneh. You need to change their values to the length of the filler IF there is a filler with AND if the top shelf is on the far left or far right partition accordingly.

**Comment by JJanneh** [comment] 2021-02-10 19:46
The topshelf covers the filler. Tested this on several Partitions ![Screenshot (206)](https://user-images.githubusercontent.com/76751383/107562963-b1aeea00-6b9d-11eb-8be3-32666d3b2ab5.png)

**Comment by kategodfrey** [comment] 2021-02-10 22:41
This looks good and will be awesome for designers so they don't have to go through multiple steps. 

Two (small) things:

1) If I set up my partitions and put a topshelf in then go back to my partition prompts and add a filler, the topshelf stays put- like it didn't get the message that filler was added. I can delete the topshelf and drag a new one in and it works just fine so this is a minor thing.

2) in the partition prompt where you add filler, the left filler creates an entire line
![image](https://user-images.githubusercontent.com/63115502/107581964-0c544000-6bb6-11eb-9b0c-8b976a6c18ce.png)
Where as when I select the right filler it stays on it's side:
![image](https://user-images.githubusercontent.com/63115502/107582090-41609280-6bb6-11eb-9317-0ec97a56037e.png)

small issue, I know but I thought I would point it out.

good work @JJanneh !!

**Comment by TylerStandage** [comment] 2021-02-11 01:50
@TedCC1209  please confirm that we want to automatically update the extension of the topshelf to include the length of the filler not just at time of placement, but for every/any update made after placement. Let me and J know if you have any questions.

**Comment by TedCC1209** [comment] 2021-02-11 16:31
Yes, preferably it would adjust when changes are made after the initial insertion of the topshelf.

**Comment by TylerStandage** [comment] 2021-02-15 18:37
@JJanneh see Ted's confirmation above.  Still need to ensure that if a filler is added or edited after a top shelf has been added, then the top shelf should automatically adjust to the new measurements.

**Comment by JJanneh** [comment] 2021-02-16 22:09
Ready to Test
@TylerStandage @TedCC1209 after working with Ted he explained how the functions worked and demonstrated the proper syntax. So now when filler is added or edited after a top shelf has been added, then the top shelf automatically is adjusted to the new measurements of the L/R Filler .
![Screenshot (312)](https://user-images.githubusercontent.com/76751383/108127637-c50ff880-7068-11eb-8bb7-fad078eb209c.png)

**Comment by TylerStandage** [comment] 2021-02-16 23:22
@JJanneh  awesome, I see that the length does adjust to new lengths, doesn't snap back to the pard with a change in filler length, and that the topshelf also adjusts if you change the width of the entire section or adjust the opening widths. 

Also, note that the fields now show across just half the prompt window and only appear when one of the boxes is checked. One thing we discussed that is not finished here is to have the "add hutch backing" checkbox appear only when a "down extension" box is checked.  @JJanneh can you update that piece as well? 

@TedCC1209 @sarahhightower @kategodfrey  can you take a look and say if you're satisfied with the top shelf adjustments? Once we have that verified and the hutch checkbox update, we should be good to go.

**Comment by sarahhightower** [comment] 2021-02-17 01:48
Top shelf with filler and section adjustments worked great for me. Also, filler prompts look great! Thanks!

**Comment by JJanneh** [comment] 2021-02-17 15:40
Ready for Testing
@TylerStandage The "add hutch backing" checkbox appears only when a "down extension" Checkbox is checked
![Removal of add hutch backing](https://user-images.githubusercontent.com/76751383/108227832-85deb780-70fb-11eb-90d9-2183523090f7.PNG)
![Removal of add hutch backing 3](https://user-images.githubusercontent.com/76751383/108227935-9ee76880-70fb-11eb-8418-ce5603ed7469.PNG)

**Comment by TylerStandage** [comment] 2021-02-17 17:32
@JJanneh looks like it shows up under both the left and right side.  The hutch backing should only show up once on the left side.

Also, I've continued the confusion between this issue and the one focused on the filler extension options (custom_partition_depth). @ClassyTeddy, we will need to ensure we don't have any code collisions between these two issues when we merge. If we should move any partition depth changes that have gone into this topshelf covering filler branch ( relating to issue #288) over to the Custom Partition Depth branch, please let us know so we don't lose any of the progress made on this branch.

**Comment by ClassyTeddy** [comment] 2021-02-17 17:43
I have primarily been working on the `Topshelf-covering-filler` branch. I think that in order to avoid an issue from occurring in the future, @JJanneh try to work on both issue #288 and issue #221 on the `Topshelf-covering-filler` branch. Then, when both issues are done, we will merge just the one branch. This will help avoid any merging issues as well as should help avoid confusion.

**Comment by JJanneh** [comment] 2021-02-17 18:27
@ClassyTeddy Ok will continue updates only on Topshelf-covering-filler branch. Thanks for the guidance. @TylerStandage Ok Removed the "Add Hutch Backing" from the Right side Checkbox area. Per request.

**Comment by TylerStandage** [comment] 2021-02-17 20:43
Thanks @JJanneh !  Let update it a bit more.  Right now it only appears if the Extend Left Partition box is checked.  Let's also have it appear if the Extend Right Partition is checked.  So if either is checked, the designer will see that it is an option.

**Comment by JJanneh** [comment] 2021-02-18 13:52
@TylerStandage Updated

**Comment by JJanneh** [comment] 2021-02-18 18:23
@TylerStandage As per our earlier conversation about "Extend Left Partition" and "Extend Right Partition" prompt both must be checked to allow Prompt menu to show up and  "Add Hutch Backing"  prompt only on the Left side. 
![Screenshot (337)](https://user-images.githubusercontent.com/76751383/108403221-bc8bff00-71db-11eb-91c6-dad7c07eff92.png)

**Comment by TylerStandage** [comment] 2021-02-18 18:39
@JJanneh thanks, looks like the hutch option only shows when both extend left and extend right boxes are checked!  Looks like the fields now don't show up when only one of the extend left/right boxes is checked now, though. Can you re-insert the fields for each when only that side is checked?

![image](https://user-images.githubusercontent.com/77167318/108405013-6f0c9380-71d5-11eb-95ef-b994035c97e2.png)

The above is when only one is checked. The below is when both are checked. 

![image](https://user-images.githubusercontent.com/77167318/108405066-7fbd0980-71d5-11eb-9808-d1082ba066a2.png)

**Comment by JJanneh** [comment] 2021-02-18 21:54
@TylerStandage Topshelf-covering-filler branch Updated 
**Edgebanding and Capping Testing** on Option-to-edge-bottom-edge branch

**Comment by TylerStandage** [comment] 2021-02-18 22:18
@JJanneh thanks, looks like the field are back!  

I also noticed that the hutch in the back spans the entire width, including outside the partitions (wall to wall, essentially). The length of the hutch backing should be the width between the inner edges of the two partitions that are extended downward. Can you update?

**Comment by JJanneh** [comment] 2021-02-19 15:07
@TylerStandage @ClassyTeddy Ok Updating 
![Screenshot (358)](https://user-images.githubusercontent.com/76751383/108521869-68d7ef00-7289-11eb-9cd0-944c143e10e4.png)
![Screenshot (359)](https://user-images.githubusercontent.com/76751383/108521894-6ffefd00-7289-11eb-8168-1878c31560fa.png)

**Comment by TylerStandage** [comment] 2021-02-19 16:20
Thanks @JJanneh !  For clarity, see the image below.  The hutch backing extends beyond the outside pards. It should sit within the two outside pards, including when opening sizes are modified.

![image](https://user-images.githubusercontent.com/77167318/108531202-4ba42000-728b-11eb-9dd4-de8f324ab6c8.png)

**Comment by JJanneh** [comment] 2021-02-23 21:51
@TylerStandage @ClassyTeddy Thanks!
 The hutch backing no longer extends beyond the outside pards. It currently sits within the two outside pards, including when opening sizes are modified. This has been completed as well as when you check/uncheck the prompt for the L/R Filler the value also clears to zero.
 ![Screenshot (428)](https://user-images.githubusercontent.com/76751383/108912222-943e3f00-75e5-11eb-9238-7b5aae1e6ee9.png)
![Screenshot (430)](https://user-images.githubusercontent.com/76751383/108912929-8937de80-75e6-11eb-956d-81fe6c1371db.png)

**Comment by TylerStandage** [comment] 2021-02-23 22:03
@JJanneh thanks, looks good!!  Officially moving this to testing.  @TedCC1209 and I will take a look again to formally pass this one off.

**Comment by TylerStandage** [comment] 2021-02-23 22:04
#221  is also being testing on the topshelf covering filler branch.

**Comment by TedCC1209** [comment] 2021-02-24 16:38
Tested this issue https://github.com/CCDevNelson/Snap-Updates/issues/288, Custom Partition Depth https://github.com/CCDevNelson/Snap-Updates/issues/221, and the hutch backing issue on the Topshelf-covering-filler branch.

Everything is looking really good, great work. The only thing that doesn't seem to be working is having the topshelf dynamically adjust when the filler width amount is changed after the topshelf is put in. Otherwise, I didn't find any other issues with my initial testing. Not sure if we thought that was good to go or if we were going to address it later?

Side note--the menu subtitles for Filler Options and Left/Right End Options look correct in this branch as compared to my note in https://github.com/CCDevNelson/Snap-Updates/issues/272#issuecomment-785189940 for the menu in the Option-to-edge-bottom-edge branch.

**Comment by ClassyTeddy** [comment] 2021-02-24 16:46
> The only thing that doesn't seem to be working is having the topshelf dynamically adjust when the filler width amount is changed after the topshelf is put in 

This should be working, we can take a look at it later @JJanneh

**Comment by JJanneh** [comment] 2021-02-24 21:10
@TedCC1209 @TylerStandage Currently working is having the topshelf dynamically adjust when the filler width amount is changed after the topshelf is put in. @ClassyTeddy Thanks

**Comment by TylerStandage** [comment] 2021-02-25 16:20
@JJanneh confirmed the topshelf is working, thanks! Ready to merge. 

@ClassyTeddy for reference/reminder when merging:  #221 and #288 are on the topshelf-covering-filler branch, as are the correct menu subtitles as requested by Ted. #272 and #253 are on the option to-edge-bottom-edge branch.

**Closed** 2021-03-29 13:49 UTC
Labels: enhancement
