### ISSUE TITLE
v1.2.2 update testing

### ISSUE THREAD

**Issue by TedCC1209** [CCDevNelson/Snap-Updates#274] opened 2021-01-14 17:17 UTC
Please test the update going from 1.2.1 to 1.2.2 by opening the branch Version-1.2.1 and report any issues found in this thread.

REMINDER: ALWAYS discard the changes the update makes to the 'Version-1.2.1' branch. Never commit the changes the updater makes when testing the update process.

**Comment by TedCC1209** [comment] 2021-01-14 17:22
The colors that were gotten rid of in https://github.com/CCDevNelson/Snap-Updates/issues/189 are still showing up after doing the update.

![discontinued colors](https://user-images.githubusercontent.com/61025894/104625729-4c291580-5652-11eb-8cfb-b68f57b1fb4e.png)

**Comment by ClassyTeddy** [comment] 2021-01-14 17:30
I can confirm that they are not currently on the master branch. I believe the issue is that the discontinued colors are not in the snap_db folder, which is the only folder that gets changed when updating, but are instead in the data/materials folder. 

@RyanMDev a possible solution would be moving all the materials we want over to snap_db/materials, then only looking for .blend files in the one location rather than both, correct?

**Comment by RyanMDev** [comment] 2021-01-14 19:32
This is happening because the material files will still exist on a user's
installation in the data/materials folder. These materials also still exist
in the CCItems list which is why they are being searched for and added if
found.

Is there a reason that these discontinued materials need to be left in the
CCItems.csv list?

**Comment by TedCC1209** [comment] 2021-01-14 19:55
For this release and iteration feel free to just delete them from the csv. In the future we may want to figure out a way to keep old colors on the list for reference purposes, but go ahead and delete the rows of the discontinued colors now if that will fix this issue for the release.

Thanks, Ted

**Comment by TedCC1209** [comment] 2021-01-14 19:58
Or can we just add the word "Discontinued" to the Display Name or whatever field SNaP is looking for to match the material file?

**Comment by ClassyTeddy** [comment] 2021-01-14 20:14
I have made the changes on the `Wrong-Colors-Exporting` branch. We won't really be able to test it however until the change gets put into the release.

**Comment by RyanMDev** [comment] 2021-01-14 21:45
I have merged these changes for CCItems into master and updated the release candidate for testing.

Adding "DISCONTINUED" to the display name will be okay for these few colors and this release. Moving forward into SNaP 2.0, if we want to keep discontinued colors in CCItems.csv, it will be a better idea to use an additional field/column for determining if the color is discontinued or not.

**Comment by kategodfrey** [comment] 2021-01-14 23:23
The 2D views are not showing the dotted lines behind doors representing hang or shelves. We have an issue that addresses this that @AntonioGloria fixed. #212 . Is that branch to a point it can be merged? 
This is currently what it's showing up as. The middle left doors I have open 50% and the middle right doors are closed. I also seemed to have lost the partition that divides them and part of the right KD.

![image](https://user-images.githubusercontent.com/63115502/104660894-af33a000-5684-11eb-8f38-8e915a612b6e.png)

**Comment by TedCC1209** [comment] 2021-01-14 23:26
Yes^^ I think we overlooked having that branch merged. It would be great if we could have it in this update

**Comment by RyanMDev** [comment] 2021-01-15 00:03
I merged this branch on 1/5 - [Pull Request #288](https://github.com/CCDevNelson/SNaP-Dev/pull/288)

Any commits made to this branch after that date have not been reviewed and need to have a pull request created for them.

**Comment by TedCC1209** [comment] 2021-01-15 00:09
> I merged this branch on 1/5 - [Pull Request #288](https://github.com/CCDevNelson/SNaP-Dev/pull/288)
> 
> Any commits made to this branch after that date have not been reviewed and need to have a pull request created for them.

Thank you for looking into that Ryan. @AntonioGloria it looks like your fixes in https://github.com/CCDevNelson/Snap-Updates/issues/212 are good to go on this same branch? @ClassyTeddy please create a pull request and we will do extra testing tomorrow.

Thank you everyone

**Comment by RyanMDev** [comment] 2021-01-15 17:19
I have merged the new pull request "#297 - 3 d labels" and updated the release candidate for testing.

**Comment by TedCC1209** [comment] 2021-01-15 17:26
Thank you for being so prompt @RyanMDev 

@kategodfrey @sarahhightower please test again today and let us know your results. Thanks, Ted

**Comment by sarahhightower** [comment] 2021-01-15 17:37
The shelves and rods are appearing, but this appears to have caused some issues with labeling. I don't see the closet height, the ceiling height, or the toe kick. Also, the dashes are missing from the depths. 

![2D Views pdf - Adobe Acrobat Reader DC 1_15_2021 10_33_15 AM](https://user-images.githubusercontent.com/72047269/104759662-7abff280-571d-11eb-80e0-51217d5b4950.png)

**Comment by TedCC1209** [comment] 2021-01-15 17:39
> The shelves and rods are appearing, but this appears to have caused some issues with labeling. I don't see the closet height, the ceiling height, the toe kick height, or the pard height. Also, the dashes are missing from the depths.
> 
> ![2D Views pdf - Adobe Acrobat Reader DC 1_15_2021 10_33_15 AM](https://user-images.githubusercontent.com/72047269/104759662-7abff280-571d-11eb-80e0-51217d5b4950.png)

@AntonioGloria please advise. We need to get this sorted out. Thanks, Ted

**Comment by RyanMDev** [comment] 2021-01-15 17:42
Is this happening on the master branch as well? or only when testing the update from 1.2.1 to 1.2.2?

**Comment by TedCC1209** [comment] 2021-01-15 17:44
These look like the same issues the hot fix in https://github.com/CCDevNelson/Snap-Updates/issues/265 addressed. That was merged with the master before but perhaps the latest merge of Antonio's branch overrode them? I will check the master branch as well as the update from 1.2.1 to 1.2.2

**Comment by AntonioGloria** [comment] 2021-01-15 17:50
This is how the 2D views are looking on my end. I'm not sure if anything is missing in them.

![Current_2D_Views_Renders](https://user-images.githubusercontent.com/74732175/104761010-d7c0a600-5727-11eb-890e-aa7ce1efa47c.png)

**Comment by sarahhightower** [comment] 2021-01-15 17:53
> Is this happening on the master branch as well? or only when testing the update from 1.2.1 to 1.2.2?

This happened when I was testing the Master branch, 1.2.2. The same thing happened for Katie when she tested that branch as well. We will now test 1.2.1 and report back.

**Comment by RyanMDev** [comment] 2021-01-15 17:57
Alright, I will need to fix this. Let me take a look.

**Comment by RyanMDev** [comment] 2021-01-15 18:37
Alright, this is ready to test on the master branch.

**Comment by RyanMDev** [comment] 2021-01-15 19:18
Alright, 2D views have been fixed, ready to test on master branch. CCDevNelson/SNaP-Dev@ad80b515ff9027bb0cdefa5b0486ef5a38c296f1

**Comment by kategodfrey** [comment] 2021-01-15 19:28
![image](https://user-images.githubusercontent.com/63115502/104769828-1e64cf00-572d-11eb-803a-c6643f492ceb.png)
 Measurements are back, but the dashed lines of what is behind the doors are now gone.

**Comment by kategodfrey** [comment] 2021-01-15 19:29
Plan view:

![image](https://user-images.githubusercontent.com/63115502/104769922-46543280-572d-11eb-8165-f63bcb917922.png)

**Comment by sarahhightower** [comment] 2021-01-15 19:30
Same scenario with me. 

![2D Views pdf - Adobe Acrobat Reader DC 1_15_2021 12_28_28 PM](https://user-images.githubusercontent.com/72047269/104770066-6b48a580-572d-11eb-9d45-50eca6dc82f7.png)

**Comment by kategodfrey** [comment] 2021-01-15 19:31
> Plan view:
> 
> ![image](https://user-images.githubusercontent.com/63115502/104769922-46543280-572d-11eb-8165-f63bcb917922.png)

Also my doors in the corners each have shelves in them but the plan view does not reflect that. Left side has 8 shelves, right has 11.

**Comment by TedCC1209** [comment] 2021-01-15 20:02
> > Plan view:
> > ![image](https://user-images.githubusercontent.com/63115502/104769922-46543280-572d-11eb-8165-f63bcb917922.png)
> 
> Also my doors in the corners each have shelves in them but the plan view does not reflect that. Left side has 8 shelves, right has 11.

@AntonioGloria is it looking in the door prompts for shelves added through there rather than through a shelf stack?

**Comment by AntonioGloria** [comment] 2021-01-15 20:36
It doesn't seem to do that. Apparently, it only counts and labels shelves that were added separately.

**Comment by TedCC1209** [comment] 2021-01-15 20:41
> Same scenario with me.
> 
> ![2D Views pdf - Adobe Acrobat Reader DC 1_15_2021 12_28_28 PM](https://user-images.githubusercontent.com/72047269/104770066-6b48a580-572d-11eb-9d45-50eca6dc82f7.png)

@ClassyTeddy this is showing a middle KD between the two drawers above the hamper--I think there shouldn't be based on our fix from https://github.com/CCDevNelson/Snap-Updates/issues/188. It also shows a double bottom KD that should be restricted by our fix in https://github.com/CCDevNelson/Snap-Updates/issues/111. Are those fixes being reflected in the master branch / update?

**Comment by TedCC1209** [comment] 2021-01-15 20:42
> It doesn't seem to do that. Apparently, it only counts and labels shelves that were added separately.

How long would it take you to add the count and labels for shelves from the door prompts?

**Comment by AntonioGloria** [comment] 2021-01-15 21:07
I think it might take me around 2-3 hours.

**Comment by ClassyTeddy** [comment] 2021-01-15 21:24
> @ClassyTeddy this is showing a middle KD between the two drawers above the hamper--I think there shouldn't be based on our fix from #188. It also shows a double bottom KD that should be restricted by our fix in #111. Are those fixes being reflected in the master branch / update?

It looks like #188 never got merged, but #111 did. I will look into why there is a duplicate KD, and I will make a pull requests for #188

**Comment by ClassyTeddy** [comment] 2021-01-15 22:19
Hey @TedCC1209 I couldn't mimic the double bottom KD issue. Are there any other setting you have turned on in the door, drawer, or partition prompts that might be affecting the number of KD's? I tried having a base partition and a hanging partition, I tried placing the assemblies in different orders, and I tried placing two 1 drawer stacks instead of one 2 drawer stack, but I never got a duplicate bottom KD.

**Comment by sarahhightower** [comment] 2021-01-15 22:30
The last time it happened I had brought in drawers and then changed my mind about using then. So I deleted them and then replaced them with a hamper. I just tried this again and the same thing happened. 

![2D Views pdf - Adobe Acrobat Reader DC 1_15_2021 3_28_29 PM](https://user-images.githubusercontent.com/72047269/104784894-7956f000-5746-11eb-87fa-47a7c47c3766.png)

**Comment by TedCC1209** [comment] 2021-01-15 22:32
> Hey @TedCC1209 I couldn't mimic the double bottom KD issue. Are there any other setting you have turned on in the door, drawer, or partition prompts that might be affecting the number of KD's? I tried having a base partition and a hanging partition, I tried placing the assemblies in different orders, and I tried placing two 1 drawer stacks instead of one 2 drawer stack, but I never got a duplicate bottom KD.

I just mimicked what @sarahhightower had in her picture -- put in the partitions (did not make it floor-based section, meaning I did not click the down arrow), put in the hamper, put in the two drawers, then put in the door, and it came up with two KDs at the bottom.

**Comment by TedCC1209** [comment] 2021-01-15 22:33
![Untitled](https://user-images.githubusercontent.com/61025894/104785135-12860680-5747-11eb-86c5-361823608e83.png)

**Comment by ClassyTeddy** [comment] 2021-01-15 23:07
@TedCC1209 Figured it out. If you place doors above **anything** and select the `Fill Opening` option, they assume that they are not above something and they place a duplicate KD at the bottom of the partition. If you unselect bottom KD in the door prompts, or if at any point you open the partition prompts and make a change, like swapping over to the construction tab, the duplicate KD will be removed. So the `Fill Opening` option is what is causing problems.

**Comment by TedCC1209** [comment] 2021-01-15 23:10
> @TedCC1209 Figured it out. If you place doors above **anything** and select the `Fill Opening` option, they assume that they are not above something and they place a duplicate KD at the bottom of the partition. If you unselect bottom KD in the door prompts, or if at any point you open the partition prompts and make a change, like swapping over to the construction tab, the duplicate KD will be removed. So the `Fill Opening` option is what is causing problems.

Ah okay, nice work figuring that out. Good to know. That fill opening option seems to be causing a bunch of issues (backing, etc.). For this update, let's not worry about it then and we will address for the next update.

**Comment by ClassyTeddy** [comment] 2021-01-15 23:14
The reason this wasn't an issue with duplicate KD's before is because of the changes we made with #63 and #269. Where as before, when the door was placed above something, I told it not to do the dynamic KD's because I couldn't easily find the partition anymore. But our recent changes made that a lot easier, but now, since it **always** knows what partition it is in, there is no logic to stop it from duplicating that KD only when the fill opening option is selected. The for fill opening currently assumes that it is the only thing in the partition.

**Comment by kategodfrey** [comment] 2021-01-15 23:26
> > @TedCC1209 Figured it out. If you place doors above **anything** and select the `Fill Opening` option, they assume that they are not above something and they place a duplicate KD at the bottom of the partition. If you unselect bottom KD in the door prompts, or if at any point you open the partition prompts and make a change, like swapping over to the construction tab, the duplicate KD will be removed. So the `Fill Opening` option is what is causing problems.
> 
> Ah okay, nice work figuring that out. Good to know. That fill opening option seems to be causing a bunch of issues (backing, etc.). For this update, let's not worry about it then and we will address for the next update.

Agreed

**Comment by RyanMDev** [comment] 2021-01-15 23:31
> ![image](https://user-images.githubusercontent.com/63115502/104769828-1e64cf00-572d-11eb-803a-c6643f492ceb.png)
> Measurements are back, but the dashed lines of what is behind the doors are now gone.

Fix for this issue is available: CCDevNelson/SNaP-Dev@eb690508307329ac1124e290614a79751facfca5

**Comment by TedCC1209** [comment] 2021-01-15 23:54
> > ![image](https://user-images.githubusercontent.com/63115502/104769828-1e64cf00-572d-11eb-803a-c6643f492ceb.png)
> > Measurements are back, but the dashed lines of what is behind the doors are now gone.
> 
> Fix for this issue is available: [CCDevNelson/SNaP-Dev@eb69050](https://github.com/CCDevNelson/SNaP-Dev/commit/eb690508307329ac1124e290614a79751facfca5)

Looks to be working for me on the Master branch:

![image](https://user-images.githubusercontent.com/61025894/104789362-1cf9cd80-5752-11eb-93a1-46a3ff7b909c.png)

Though the program while drawing did seem a little slower than usual (not sure if related to this fix)

**Comment by AntonioGloria** [comment] 2021-01-16 01:20
I have changed the shelf counting in plan views to also include shelves added via door prompts.
![2021-01-15 18_45_23-Window](https://user-images.githubusercontent.com/74732175/104793095-97344d00-5766-11eb-9a5b-74116549e640.png)
![2021-01-15 18_46_40-Window](https://user-images.githubusercontent.com/74732175/104793096-9b606a80-5766-11eb-9fec-706a3bbb4ccf.png)
This fix is here: https://github.com/nailsonlandim/SNaP-Dev/tree/2dviews-add-door-prompt-shelves-to-plan-view-shelf-count

**Comment by TedCC1209** [comment] 2021-01-16 16:12
> Hi @TedCC1209,
> I have changed the shelf counting in plan views to also include shelves added via door prompts.
> This fix is here: https://github.com/nailsonlandim/SNaP-Dev/tree/2dviews-add-door-prompt-shelves-to-plan-view-shelf-count

Worked for me:

![image](https://user-images.githubusercontent.com/61025894/104816831-d1d7cd00-57da-11eb-8c93-dc4ca415972a.png)

@ClassyTeddy can you do a pull request for this please? @sarahhightower @kategodfrey please test if you can.

**Comment by sarahhightower** [comment] 2021-01-18 03:10
Tested https://github.com/nailsonlandim/SNaP-Dev/tree/2dviews-add-door-prompt-shelves-to-plan-view-shelf-count. 

Shelves and hanging component appear behind doors, but the shelf counts appear off.  On the left side I have 1 adjustable shelf and 3 KD shelves but the plan view says 2 shelves. On the right side I have two adjustable shelves and 2 KDs but the plan view says 3 shelves.  I initially thought this might relate to issue #212, but I can't understand why the right section would show 3 shelves? Are only the shelves behind the doors being counted (with the exception of the top KD)? Or could it be that I reduced the medium hang section with three shelves to two after I added the component?

![Plan View](https://user-images.githubusercontent.com/72047269/104867226-a4d00b00-58fd-11eb-9a58-a9d63eef4346.png)

![Elevation](https://user-images.githubusercontent.com/72047269/104867231-a7cafb80-58fd-11eb-8032-1ca6232dab1d.png)

**Comment by TedCC1209** [comment] 2021-01-18 04:58
My guess is that the logic counts the bottom KD of a door assembly as a shelf no matter what, but @AntonioGloria would have to confirm that. If we can exclude from counting as a shelf the bottom KD for Tall doors when there is a hang in the same section I think that would address what @sarahhightower  pointed out here.

**Comment by RyanMDev** [comment] 2021-01-18 18:20
> Tested https://github.com/nailsonlandim/SNaP-Dev/tree/2dviews-add-door-prompt-shelves-to-plan-view-shelf-count.
> 
> Shelves and hanging component appear behind doors, but the shelf counts appear off. On the left side I have 1 adjustable shelf and 3 KD shelves but the plan view says 2 shelves. On the right side I have two adjustable shelves and 2 KDs but the plan view says 3 shelves. I initially thought this might relate to issue #212, but I can't understand why the right section would show 3 shelves? Are only the shelves behind the doors being counted (with the exception of the top KD)? Or could it be that I reduced the medium hang section with three shelves to two after I added the component?

@sarahhightower, can you share the room/blend file you created to test to get these results?

**Comment by sarahhightower** [comment] 2021-01-18 18:40
Sure. Here you go. 

https://drive.google.com/file/d/1x_I1qXPe1wlluWQs0dkpzgB3nuO6fN2x/view?usp=sharing

**Comment by TedCC1209** [comment] 2021-01-18 19:07
@AntonioGloria is also working on a fix--he has the exclusion for counting bottom KDs as a shelf when it is both 1. a tall door and 2. there is a hang assembly in the opening. However, he let me know he found an issue counting the shelves in hang sections so he is looking into that as well.

**Comment by RyanMDev** [comment] 2021-01-18 19:25
Alright then, I won't step on his toes, unless my help is needed.

**Comment by TedCC1209** [comment] 2021-01-18 19:27
@AntonioGloria can you let us know how this is going? Do you want to post what you have so far and see if others can help collaborate on a fix for the remaining parts you are still working on?

**Comment by AntonioGloria** [comment] 2021-01-18 19:41
Sure, let me share where this stands at the moment:
I am able to account for when a door is defined as "Tall" to not count its bottom KD as a shelf. But I noticed this didn't work in the example provided in the Drive link above, because in that room the door is set to "Upper" and to "Fill Opening", which can produce something that looks very similar to a Tall Door. So should I account for these factors as well?

**Comment by TedCC1209** [comment] 2021-01-18 19:49
> Sure, let me share where this stands at the moment:
> I am able to account for when a door is defined as "Tall" to not count its bottom KD as a shelf. But I noticed this didn't work in the example provided in the Drive link above, because in that room the door is set to "Upper" and to "Fill Opening", which can produce something that looks very similar to a Tall Door. So should I account for these factors as well?

Ah yes, I see that. A user should be taught to make those "Tall" doors since that is what they are, then the handle placement would automatically go to 40" (it looks like @sarahhightower kept it as an upper door, filled opening, and then manually put the handles at 39"). So, no, I don't think we need to account for all of that.

By the way--we still need to keep the bottom KD of a tall door counting as a shelf  in situations where there isn't a hang there--if it is just shelves behind the doors then we want it to count that bottom KD as a shelf. So, please make sure that the exception is more narrow than just excluding bottom KDs of tall door assemblies--it needs to not count the bottom KD as a shelf for when it is both 1. a tall door and 2. there is a hang assembly in the opening.

**Comment by RyanMDev** [comment] 2021-01-18 23:53
I see a pull request for Antonio's WIP.

Is this the only thing to finish here?

> we still need to keep the bottom KD of a tall door counting as a shelf in situations where there isn't a hang there--if it is just shelves behind the doors then we want it to count that bottom KD as a shelf. So, please make sure that the exception is more narrow than just excluding bottom KDs of tall door assemblies--it needs to not count the bottom KD as a shelf for when it is both 1. a tall door and 2. there is a hang assembly in the opening.

**Comment by TedCC1209** [comment] 2021-01-18 23:55
Yes, once Antonio and Nailson finish that up it's all we need to add and then we are good to push the auto update

**Comment by AntonioGloria** [comment] 2021-01-19 00:32
Hi @TedCC1209 and @RyanMDev,

We have a fix for the shelf counting issue.

The fix is here: https://github.com/nailsonlandim/SNaP-Dev/tree/2dviews-add-door-prompt-shelves-to-plan-view-shelf-count

**Comment by TedCC1209** [comment] 2021-01-19 00:44
> Hi @TedCC1209 and @RyanMDev,
> 
> We have a fix for the shelf counting issue.
> 
> The fix is here: https://github.com/nailsonlandim/SNaP-Dev/tree/2dviews-add-door-prompt-shelves-to-plan-view-shelf-count

Thanks! In my initial testing it looks good to me.

@RyanMDev I think we are good to go when this is merged. I say go ahead and merge Nailson's latest pull request and send out the auto update when you are ready.  

Thank you for everyone's work on this! 

@kategodfrey @sarahhightower @SeanRadvan please be ready to provide us feedback with anything that users may find that we missed in our testing. But also, please provide positive feedback too! There have been a lot of great improvements I hope you all and they are enjoying.

Thanks, 

Ted

**Closed** 2021-01-19 18:54 UTC
Labels: enhancement
