### ISSUE TITLE
Door Insert traceback issue

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#97] opened 2020-06-18 16:36 UTC
Cannot insert doors into plans now. It comes back with the following errors:

![image](https://user-images.githubusercontent.com/61025894/85047559-de158200-b146-11ea-9f17-800112e010bc.png)

The door ends up randomly in space:

![image](https://user-images.githubusercontent.com/61025894/85047632-f5ed0600-b146-11ea-871e-ef39c99e8f2d.png)

This means issue #94 likely doesn't have to do with islands, specifically.

Teddy/Ryan, please make this highest priority.

Thanks, Ted

**Comment by ClassyTeddy** [comment] 2020-06-18 16:49
I know what the issue is, looks like it was because a line of code went missing in a merge. I had fixed it on blind corner panels, but I thought it was just on my branch. I will do a quick fix and just commit it to the master.

**Comment by ClassyTeddy** [comment] 2020-06-18 16:56
This option should be fixed and can be tested on the master.

**Closed** 2020-06-18 17:07 UTC
Labels: bug
