### ISSUE TITLE
Topshelf label doesn't show room name or project name 

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#109] opened 2020-07-09 18:11 UTC
The topshelf label is also missing the project name and the room name on the label like other parts have. Here is a topshelf label:

![image](https://user-images.githubusercontent.com/61025894/87075233-e0fb1400-c1d4-11ea-88b2-c185c4d33996.png)

Here is a KD shelf label with the project and room names on them:

![image](https://user-images.githubusercontent.com/61025894/87075295-f708d480-c1d4-11ea-831d-9ad6e78f765b.png)

**Comment by TEDSTANDAGE** [comment] 2020-07-16 18:01
Mark @CCDevNelson is this something just on your end or is there something missing in the XML for topshelf that we need to add?

**Comment by CCDevNelson** [comment] 2020-07-16 18:12
Ted,
I'm pretty sure all the information is there so this could just be in the label print. I will have to look into this more once I'm back at the office cause I'm not able to get into that from here.

**Comment by TEDSTANDAGE** [comment] 2020-09-05 18:30
@CCDevNelson Just following up on this, please advise. Thanks

**Comment by CCDevNelson** [comment] 2020-09-08 16:11
This post needs to be deleted...it's just a duplicate of #107

**Comment by TEDSTANDAGE** [comment] 2020-09-08 16:23
> This post needs to be deleted...it's just a duplicate of #107

Not a duplicate. This is about the room name and project name not being on the label. 107 is about the edgebanding diagram not being on the label.

**Comment by CCDevNelson** [comment] 2020-09-08 17:10
It is in the fact that NO label changes have been implemented at all. If something is not showing up on the CURRENT labels, that is because they are the old labels. No changes to the labeling have been placed out on the shop floor. If there are things missing on the "old" labels, such as the Top Shelf, it's due to the fact we changed from doing Full Lengths to different sizes and the code in the old COS is probably being skipped over now and not passing the info through the way it use to. But, this is not part of the SNaP labels, or the info that would be passed through with an XML, at this point in time.

**Comment by TEDSTANDAGE** [comment] 2020-09-08 17:19
> It is in the fact that NO label changes have been implemented at all. If something is not showing up on the CURRENT labels, that is because they are the old labels. No changes to the labeling have been placed out on the shop floor. If there are things missing on the "old" labels, such as the Top Shelf, it's due to the fact we changed from doing Full Lengths to different sizes and the code in the old COS is probably being skipped over now and not passing the info through the way it use to. But, this is not part of the SNaP labels, or the info that would be passed through with an XML, at this point in time.

Mark, the original post was from the SNaP labels printed in July for test SNaP jobs, and the top shelf labels were printing off differently than all other parts (missing project/room info, no edgebanding diagram, etc.). All I was asking was if something needed to be changed in the XML. It sounds like the answer is no.

**Closed** 2020-09-24 17:53 UTC
Labels: enhancement
